/// <auto-generated>
/// This file is auto-generated by UniEnum.
/// </auto-generated>

namespace UnityConstantsGenerator
{
    public enum LayerId
    {
        /// <summary>
        /// Default
        /// </summary>
        Default = 0,

        /// <summary>
        /// TransparentFX
        /// </summary>
        TransparentFX = 1,

        /// <summary>
        /// Ignore Raycast
        /// </summary>
        IgnoreRaycast = 2,

        /// <summary>
        /// WaterSurface
        /// </summary>
        WaterSurface = 3,

        /// <summary>
        /// Water
        /// </summary>
        Water = 4,

        /// <summary>
        /// UI
        /// </summary>
        UI = 5,

        /// <summary>
        /// Player
        /// </summary>
        Player = 6,

        /// <summary>
        /// Interactable
        /// </summary>
        Interactable = 7,

        /// <summary>
        /// NPC
        /// </summary>
        NPC = 8,

        /// <summary>
        /// Ground
        /// </summary>
        Ground = 9,

        /// <summary>
        /// WaterNavMeshBlocker
        /// </summary>
        WaterNavMeshBlocker = 10,

        /// <summary>
        /// Manager
        /// </summary>
        Manager = 11,

        /// <summary>
        /// UnderwaterGround
        /// </summary>
        UnderwaterGround = 12,

        /// <summary>
        /// Items
        /// </summary>
        Items = 13,

        /// <summary>
        /// Clouds
        /// </summary>
        Clouds = 14,

        /// <summary>
        /// PostProcessingVolumes
        /// </summary>
        PostProcessingVolumes = 15,

        /// <summary>
        /// Animal
        /// </summary>
        Animal = 16,

        /// <summary>
        /// Enemy
        /// </summary>
        Enemy = 26,

        /// <summary>
        /// MovingPlatform
        /// </summary>
        MovingPlatform = 27,

        /// <summary>
        /// VisualEffect
        /// </summary>
        VisualEffect = 28,

        /// <summary>
        /// Overlay
        /// </summary>
        Overlay = 29,

        /// <summary>
        /// SubCharacter
        /// </summary>
        SubCharacter = 30,

        /// <summary>
        /// Character
        /// </summary>
        Character = 31,

    }

    [System.Flags]
    public enum LayerMaskValue
    {
        /// <summary>
        /// Default
        /// </summary>
        Default = 1 << 0,

        /// <summary>
        /// TransparentFX
        /// </summary>
        TransparentFX = 1 << 1,

        /// <summary>
        /// Ignore Raycast
        /// </summary>
        IgnoreRaycast = 1 << 2,

        /// <summary>
        /// WaterSurface
        /// </summary>
        WaterSurface = 1 << 3,

        /// <summary>
        /// Water
        /// </summary>
        Water = 1 << 4,

        /// <summary>
        /// UI
        /// </summary>
        UI = 1 << 5,

        /// <summary>
        /// Player
        /// </summary>
        Player = 1 << 6,

        /// <summary>
        /// Interactable
        /// </summary>
        Interactable = 1 << 7,

        /// <summary>
        /// NPC
        /// </summary>
        NPC = 1 << 8,

        /// <summary>
        /// Ground
        /// </summary>
        Ground = 1 << 9,

        /// <summary>
        /// WaterNavMeshBlocker
        /// </summary>
        WaterNavMeshBlocker = 1 << 10,

        /// <summary>
        /// Manager
        /// </summary>
        Manager = 1 << 11,

        /// <summary>
        /// UnderwaterGround
        /// </summary>
        UnderwaterGround = 1 << 12,

        /// <summary>
        /// Items
        /// </summary>
        Items = 1 << 13,

        /// <summary>
        /// Clouds
        /// </summary>
        Clouds = 1 << 14,

        /// <summary>
        /// PostProcessingVolumes
        /// </summary>
        PostProcessingVolumes = 1 << 15,

        /// <summary>
        /// Animal
        /// </summary>
        Animal = 1 << 16,

        /// <summary>
        /// Enemy
        /// </summary>
        Enemy = 1 << 26,

        /// <summary>
        /// MovingPlatform
        /// </summary>
        MovingPlatform = 1 << 27,

        /// <summary>
        /// VisualEffect
        /// </summary>
        VisualEffect = 1 << 28,

        /// <summary>
        /// Overlay
        /// </summary>
        Overlay = 1 << 29,

        /// <summary>
        /// SubCharacter
        /// </summary>
        SubCharacter = 1 << 30,

        /// <summary>
        /// Character
        /// </summary>
        Character = 1 << 31,

    }

}

