/// <auto-generated>
/// This file is auto-generated by UniEnum.
/// </auto-generated>

namespace UnityConstantsGenerator
{
    public enum LayerId
    {
        /// <summary>
        /// Default
        /// </summary>
        Default = 0,

        /// <summary>
        /// TransparentFX
        /// </summary>
        TransparentFX = 1,

        /// <summary>
        /// Ignore Raycast
        /// </summary>
        IgnoreRaycast = 2,

        /// <summary>
        /// WaterSurface
        /// </summary>
        WaterSurface = 3,

        /// <summary>
        /// Water
        /// </summary>
        Water = 4,

        /// <summary>
        /// UI
        /// </summary>
        UI = 5,

        /// <summary>
        /// Player
        /// </summary>
        Player = 6,

        /// <summary>
        /// Interactable
        /// </summary>
        Interactable = 7,

        /// <summary>
        /// NPC
        /// </summary>
        NPC = 8,

        /// <summary>
        /// Ground
        /// </summary>
        Ground = 9,

        /// <summary>
        /// WaterNavMeshBlocker
        /// </summary>
        WaterNavMeshBlocker = 10,

        /// <summary>
        /// Manager
        /// </summary>
        Manager = 11,

        /// <summary>
        /// UnderwaterGround
        /// </summary>
        UnderwaterGround = 12,

        /// <summary>
        /// Items
        /// </summary>
        Items = 13,

    }

    [System.Flags]
    public enum LayerMaskValue
    {
        /// <summary>
        /// Default
        /// </summary>
        Default = 1 << 0,

        /// <summary>
        /// TransparentFX
        /// </summary>
        TransparentFX = 1 << 1,

        /// <summary>
        /// Ignore Raycast
        /// </summary>
        IgnoreRaycast = 1 << 2,

        /// <summary>
        /// WaterSurface
        /// </summary>
        WaterSurface = 1 << 3,

        /// <summary>
        /// Water
        /// </summary>
        Water = 1 << 4,

        /// <summary>
        /// UI
        /// </summary>
        UI = 1 << 5,

        /// <summary>
        /// Player
        /// </summary>
        Player = 1 << 6,

        /// <summary>
        /// Interactable
        /// </summary>
        Interactable = 1 << 7,

        /// <summary>
        /// NPC
        /// </summary>
        NPC = 1 << 8,

        /// <summary>
        /// Ground
        /// </summary>
        Ground = 1 << 9,

        /// <summary>
        /// WaterNavMeshBlocker
        /// </summary>
        WaterNavMeshBlocker = 1 << 10,

        /// <summary>
        /// Manager
        /// </summary>
        Manager = 1 << 11,

        /// <summary>
        /// UnderwaterGround
        /// </summary>
        UnderwaterGround = 1 << 12,

        /// <summary>
        /// Items
        /// </summary>
        Items = 1 << 13,

    }

}

