/// <auto-generated>
/// This file is auto-generated by UniEnum.
/// </auto-generated>

namespace UnityConstantsGenerator
{
    public class TagName
    {
        /// <summary>
        /// Untagged
        /// </summary>
        public static readonly string Untagged = "Untagged";

        /// <summary>
        /// Respawn
        /// </summary>
        public static readonly string Respawn = "Respawn";

        /// <summary>
        /// Finish
        /// </summary>
        public static readonly string Finish = "Finish";

        /// <summary>
        /// EditorOnly
        /// </summary>
        public static readonly string EditorOnly = "EditorOnly";

        /// <summary>
        /// MainCamera
        /// </summary>
        public static readonly string MainCamera = "MainCamera";

        /// <summary>
        /// Player
        /// </summary>
        public static readonly string Player = "Player";

        /// <summary>
        /// GameController
        /// </summary>
        public static readonly string GameController = "GameController";

        /// <summary>
        /// CinemachineTarget
        /// </summary>
        public static readonly string CinemachineTarget = "CinemachineTarget";

        /// <summary>
        /// WaypointA
        /// </summary>
        public static readonly string WaypointA = "WaypointA";

        /// <summary>
        /// WaypointB
        /// </summary>
        public static readonly string WaypointB = "WaypointB";

        /// <summary>
        /// SpeakTrigger
        /// </summary>
        public static readonly string SpeakTrigger = "SpeakTrigger";

        /// <summary>
        /// MouthSpeaker
        /// </summary>
        public static readonly string MouthSpeaker = "MouthSpeaker";

        /// <summary>
        /// BoatWaypointC
        /// </summary>
        public static readonly string BoatWaypointC = "BoatWaypointC";

        /// <summary>
        /// BoatWaypointA
        /// </summary>
        public static readonly string BoatWaypointA = "BoatWaypointA";

        /// <summary>
        /// BoatWaypointB
        /// </summary>
        public static readonly string BoatWaypointB = "BoatWaypointB";

        /// <summary>
        /// BoatWaypointD
        /// </summary>
        public static readonly string BoatWaypointD = "BoatWaypointD";

        /// <summary>
        /// WaypointC
        /// </summary>
        public static readonly string WaypointC = "WaypointC";

        /// <summary>
        /// Ground
        /// </summary>
        public static readonly string Ground = "Ground";

        /// <summary>
        /// WaypointD
        /// </summary>
        public static readonly string WaypointD = "WaypointD";

        /// <summary>
        /// BoatWaypointE
        /// </summary>
        public static readonly string BoatWaypointE = "BoatWaypointE";

        /// <summary>
        /// GravesA
        /// </summary>
        public static readonly string GravesA = "GravesA";

        /// <summary>
        /// KeyboardUI
        /// </summary>
        public static readonly string KeyboardUI = "KeyboardUI";

        /// <summary>
        /// GamepadUI
        /// </summary>
        public static readonly string GamepadUI = "GamepadUI";

        /// <summary>
        /// BoatWaypointF
        /// </summary>
        public static readonly string BoatWaypointF = "BoatWaypointF";

        /// <summary>
        /// BoatWaypointG
        /// </summary>
        public static readonly string BoatWaypointG = "BoatWaypointG";

        /// <summary>
        /// WaypointE
        /// </summary>
        public static readonly string WaypointE = "WaypointE";

        /// <summary>
        /// WaypointF
        /// </summary>
        public static readonly string WaypointF = "WaypointF";

        /// <summary>
        /// WaypointG
        /// </summary>
        public static readonly string WaypointG = "WaypointG";

        /// <summary>
        /// WaypointH
        /// </summary>
        public static readonly string WaypointH = "WaypointH";

        /// <summary>
        /// WaypointK
        /// </summary>
        public static readonly string WaypointK = "WaypointK";

    }

}

